#!/usr/bin/env bash
set -euo pipefail

# Lints markdown files and ensures the autogenerated README index is up to date.
#
# Requirements (recommended):
#   npm i -D markdownlint-cli2
#
# Optional:
#   npm i -D prettier
#
# Usage:
#   ./scripts/lint-markdown.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "$REPO_ROOT"

echo "==> Linting Markdown..."

if ! command -v npx >/dev/null 2>&1; then
  echo "npx is required (Node.js). Install Node.js and try again."
  exit 1
fi

# Prefer markdownlint-cli2 (fast, modern)
if npx --yes markdownlint-cli2 --version >/dev/null 2>&1; then
  # Default config: lint all md files
  # You can add a .markdownlint-cli2.jsonc later to customize rules.
  npx --yes markdownlint-cli2 "**/*.md"
else
  echo "markdownlint-cli2 not found. Install it with:"
  echo "  npm i -D markdownlint-cli2"
  exit 1
fi

echo "==> Verifying autogenerated README index..."
# Run generator, then fail if it changes files (i.e., README not committed after generation)

# Save current git diff state
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  BEFORE_DIFF="$(git status --porcelain)"
else
  echo "Not a git repository. Skipping index up-to-date check."
  exit 0
fi

node ./scripts/generate-index.js

AFTER_DIFF="$(git status --porcelain)"

if [[ "$BEFORE_DIFF" != "$AFTER_DIFF" ]]; then
  echo ""
  echo "ERROR: Markdown index is not up to date."
  echo "Please run: node ./scripts/generate-index.js"
  echo "and commit the updated README.md."
  echo ""
  echo "Changed files:"
  git status --porcelain
  exit 1
fi

echo "==> Markdown lint + index check passed ✅"
